stages:   
  - build
  - deploy

build-job:
  before_script: 
    - echo ${MY_ENV} > .env
    - echo ${ENV_TEST} > .env-test
  stage: build
  script:
    - docker build -t booking-api-image .

deploy-job:      
  stage: deploy  
  script:
    - docker compose -f docker-compose-ci.yml down --volumes --remove-orphans
    - docker compose -f docker-compose-ci.yml up -d

