stages:   
  - build
  - deploy

build-job:
  before_script: 
    - copy ${MY_ENV} .env
    - copy ${ENV_TEST} .test-env
  stage: build
  script:
    - docker build -t booking-api-image .

deploy-job:      
  stage: deploy  
  script:
    - docker compose up -f docker-compose-ci.yml -d
