stages:   
  - build
  - deploy

build-job:
  before_script: 
    - ${MY_ENV} > .env
    - ${ENV_TEST} > .env-test
  stage: build
  script:
    - docker build -t booking-api-image .

deploy-job:      
  stage: deploy  
  script:
    - docker compose up -f docker-compose-ci.yml -d

