stages:   
  - build
  - deploy

build-job:
  before_script: 
    - cp ${MY_ENV} .env
    - cp ${ENV_TEST} .env-test
  stage: build
  script:
    - docker build -t booking-api-image .

deploy-job:      
  stage: deploy  
  script:
    - docker compose up -f docker-compose-ci.yml -d
