services:
  booking_back_service:
    container_name: booking_back
    volumes:
      - shared_images:/app/src/static/images
    image: booking-api-image:latest
    ports:
      - "7777:8000"
    networks:
      - myNetwork   
  booking_celery_worker_service:
    container_name: booking_celery_worker
    volumes:
      - shared_images:/app/src/static/images
    image: booking-api-image:latest
    networks:
      - myNetwork     
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO --pool=solo" 
  booking_celery_beat_service:
    container_name: booking_celery_beat
    image: booking-api-image:latest
    networks:
      - myNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"
            
networks:
  myNetwork:
    external: true

volumes:
  shared_images:
