"""model users upgrade

Revision ID: 69130e8c8208
Revises: 67950dcbc11f
Create Date: 2025-01-07 23:41:42.580775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69130e8c8208"
down_revision: Union[str, None] = "67950dcbc11f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=20), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=40), nullable=False))
    op.add_column("users", sa.Column("nickname", sa.String(length=35), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "nickname")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
