"""теперь название отеля и его адрес уникальны

Revision ID: 7c326e339bbf
Revises: cf450994dc30
Create Date: 2025-04-12 22:59:45.677974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c326e339bbf"
down_revision: Union[str, None] = "cf450994dc30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hotels", ["title"])
    op.create_unique_constraint(None, "hotels", ["location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotels", type_="unique")
    op.drop_constraint(None, "hotels", type_="unique")
    # ### end Alembic commands ###
