"""model users upgrade 1.1

Revision ID: 4410f5e5864c
Revises: 69130e8c8208
Create Date: 2025-01-08 17:10:45.933510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4410f5e5864c"
down_revision: Union[str, None] = "69130e8c8208"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=20), nullable=False))
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "last_name", sa.VARCHAR(length=40), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "first_name", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###
